services:
    vue:
        build: ./vue
        ports:
            - "5173:5173"
        volumes:
            - ./vue/src:/vue/src
            - ./vue/package.json:/vue/package.json
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8080"
        volumes:
            - .:/app