services:
    vue:
        build: ./vue
        entrypoint: sh -c "npm install && npm run devhost"
        ports:
            - "5173:5173"
        volumes:
            - ./vue/src:/vue/src
            - ./vue/package.json:/vue/package.json
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8080"
        volumes:
            - .:/app
            - /app/build
            - /app/.gradle
        depends_on:
            - postgres
    postgres:
        image: postgres:16-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: mtg
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
